### PR TITLE
Fixes to all the pages, Interactivity added to all the pages expect partitions pages

### PR DESCRIPTION
**Pull request by RajvirSingh1313**

### CODE REVIEW

**Comment by RajvirSingh1313** [comment]
Why merge if it was not useful? @shard77

**Comment by shard77** [comment]
@RajvirSingh1313 your code is all broken.
Many things aren't working, the styling is badly written.
Please do not disturb and waste our time by tagging or anything else.

**Comment by RajvirSingh1313** [comment]
Then cut all of contacts with me @shard77 @D3vil0p3r

**Comment by D3vil0p3r** [comment]
On this failed activity, all of us lost. So, chill man, peace and love.

**Comment by shard77** [comment]
no peace and love, you're just a scammer @RajvirSingh1313 goodbye

**Comment by shard77** [comment]
now please don't talk anymore

**Pull request merged**
