### PR TITLE
REMOVE: redundant code and depedencies

### PR DESCRIPTION
**Pull request by mwaurawakati**
MIGRATE: v1=>v2

### CODE REVIEW

**Comment by AkechiShiro** [comment]
Seems it doesn't work yet : 
```
❯ just develop
yarn && yarn run tauri dev
yarn install v1.22.19
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
warning svelte-preprocess@5.1.3: The engine "pnpm" appears to be invalid.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 26.79s.
yarn run v1.22.19
$ /home/kenshin/opensource/aegis-gui-tauri/node_modules/.bin/tauri dev
       Error `tauri.conf.json` error on `build`: Additional properties are not allowed ('devUrl', 'frontendDist' were unexpected)
       Error `tauri.conf.json` error: Additional properties are not allowed ('app', 'bundle', 'identifier', 'productName', 'version' were unexpected)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error: Recipe `develop` failed on line 10 with exit code 1
```

**Comment by mwaurawakati** [comment]
use cargo instead. Or update just to use tauri 2.0

**Comment by AkechiShiro** [comment]
Still hitting an error : 
```
The system library `libsoup-3.0` required by crate `soup3-sys` was not found.
  The file `libsoup-3.0.pc` needs to be installed and the PKG_CONFIG_PATH environment variable must contain its parent directory.
  PKG_CONFIG_PATH contains the following:
      - /nix/store/iyyhmd6nsd44nm10w364pv03qb5x2n50-glib-2.80.3-dev/lib/pkgconfig
      - /nix/store/c8j6z63459gy7s7fjjvdj918hw0nki39-zlib-1.3.1-dev/lib/pkgconfig
      - /nix/store/y82b3izg01g56rh3q3rqcrg54hgkk8hi-libffi-3.4.6-dev/lib/pkgconfig
      - /nix/store/nlpgf5lcqkdwb1apkr6k1hf5wzhb4n42-dbus-1.14.10-dev/lib/pkgconfig
      - /nix/store/6a5kk6acn7xrccicip3f3rackgk8chps-expat-2.6.2-dev/lib/pkgconfig
      - /nix/store/c065s8sppsyrfbgv271dvhb9yld32vh7-cairo-1.18.0-dev/lib/pkgconfig
      - /nix/store/2lnaz042i8xbmxbckb47rx8kksj2al7p-fontconfig-2.15.0-dev/lib/pkgconfig
      - /nix/store/2zb1h45simijjy82rsmdrd3c6ls7vf5n-freetype-2.13.2-dev/lib/pkgconfig
      - /nix/store/ybiwzssi0k8masr6y5shysjn0zhq6pzz-bzip2-1.0.8-dev/lib/pkgconfig
      - /nix/store/0rcay5lcvmmacbcyfhsgdb1kw2pnb0lf-brotli-1.1.0-dev/lib/pkgconfig
      - /nix/store/psk5wx24nw1fcdygpbcfxlhp6crz16hb-libpng-apng-1.6.43-dev/lib/pkgconfig
      - /nix/store/i1s8sqa2adi6lb84znc26ywchfan6w4m-pixman-0.43.4/lib/pkgconfig
      - /nix/store/5fafs1ighfl4hk4zxadidmrv3na0709x-libXext-1.3.6-dev/lib/pkgconfig
      - /nix/store/rylqbcy1y8acjkmxaasbmm49bp31ndib-xorgproto-2024.1/share/pkgconfig
      - /nix/store/523gqyxmz4kapi2v43clqjzasy2lh2cr-libXau-1.0.11-dev/lib/pkgconfig
      - /nix/store/90zsycpq8b21v8vbzprf880c2hmk5cq5-libXrender-0.9.11-dev/lib/pkgconfig
      - /nix/store/v9v1r4qdj832152fr2hl689lx7fkwnkj-libX11-1.8.9-dev/lib/pkgconfig
      - /nix/store/5wdnlp7dwp5hhgjnhpbijyd309d9qkn9-libxcb-1.17.0-dev/lib/pkgconfig
      - /nix/store/f3vhjic1rhyp92951k1myiy93bk82197-at-spi2-core-2.52.0-dev/lib/pkgconfig
      - /nix/store/dp6821c0s4bbmmws3lc6nicz09lnjlgl-openssl-3.0.14-dev/lib/pkgconfig
      - /nix/store/lhb4dib4min1iql0c6ylz70d1vldjfzm-libsoup-2.74.3-dev/lib/pkgconfig
      - /nix/store/d3rrbsikj5wcxz33fa5bch0nihdivpvx-libxml2-2.12.7-dev/lib/pkgconfig
      - /nix/store/arny5a92vy06iki82gjkjxlkjym69r4d-pango-1.52.2-dev/lib/pkgconfig
      - /nix/store/wvl70hfwnkjpmnmyfplj2jk2rfdzi4kf-harfbuzz-8.4.0-dev/lib/pkgconfig
      - /nix/store/3xkdqb0156fjd1kyh37ihsr3invs4c3l-graphite2-1.3.14-dev/lib/pkgconfig
      - /nix/store/8gvp2mm288adbmij34l78i5gyxwamlwq-libXft-2.3.8-dev/lib/pkgconfig
      - /nix/store/c3nbhc101wnf038x1p1r3kri3lg4ryx6-gdk-pixbuf-2.42.12-dev/lib/pkgconfig
      - /nix/store/fx51mx5vf5i48gwrmm91zrb6sv2mfki8-libtiff-4.6.0-dev/lib/pkgconfig
      - /nix/store/xg1n38phmqiyamcparjx1iqx1fp9am32-libdeflate-1.20/lib/pkgconfig
      - /nix/store/wi4jzamfxcqmfz6fbgmfcdsmdmywl92n-libjpeg-turbo-3.0.3-dev/lib/pkgconfig
      - /nix/store/9gdhb1v6cqip5x3f67qhhh3p34c1n11w-libwebp-1.4.0/lib/pkgconfig
      - /nix/store/0dj2pdgkcsjg10m42pcfxv8xnl16ay6y-xz-5.6.2-dev/lib/pkgconfig
      - /nix/store/v56i3cdv3zr6zljygs90gwywirhbl37n-zstd-1.5.6-dev/lib/pkgconfig
      - /nix/store/v8jpq1474dkmvv7xxjdbrd1dsw5yv3nr-gtk+3-3.24.42-dev/lib/pkgconfig
      - /nix/store/6w6lbjfza6p5xiw9987g3p59bkwbisr1-fribidi-1.0.14-dev/lib/pkgconfig
      - /nix/store/28g9mr98g8f2rihfb0rkihdvkh360rp8-gsettings-desktop-schemas-46.0/share/pkgconfig
      - /nix/store/iaw1yjd4gfc3krxi6fv115mcasj51wic-libICE-1.1.1-dev/lib/pkgconfig
      - /nix/store/4njxp6za0wp8h31imvg6vkbf72zp0fm7-libSM-1.2.4-dev/lib/pkgconfig
      - /nix/store/jdvlb3cjhdhbkdkdv9bbsl9nasw9nw5b-libXcomposite-0.4.6-dev/lib/pkgconfig
      - /nix/store/kx1xivpm6fj4wpc44vwdqnbl2rvi2vmv-libXfixes-6.0.1-dev/lib/pkgconfig
      - /nix/store/77wnxz8dm0w2mpkkfklddj46mvkx0x0l-libXcursor-1.2.2-dev/lib/pkgconfig
      - /nix/store/kwj0l036zvgvg71n07c262pm8swfax68-libXdamage-1.1.6-dev/lib/pkgconfig
      - /nix/store/47rrx60rx7dg0h0sjm5b955a6xglqllh-libXi-1.8.1-dev/lib/pkgconfig
      - /nix/store/rfrzyaqnyr51jvgghvr766g7z1d4f43p-libXrandr-1.5.4-dev/lib/pkgconfig
      - /nix/store/h5j6ggf0g230bavqarsvyi23zw789fv3-libglvnd-1.7.0-dev/lib/pkgconfig
      - /nix/store/rylnk2c82rchh7x6ziqn506h0zm5pg7p-wayland-1.22.0-dev/lib/pkgconfig
      - /nix/store/a3n2vxsni6084nn5zcwy35lrvkwmz09y-wayland-1.22.0-bin/lib/pkgconfig
      - /nix/store/4f5b5iakzxb3ch64ymjzf59grvpsbrja-wayland-protocols-1.35/share/pkgconfig
      - /nix/store/g70pnzvyxrv77d8h6njs9q67yins2pfs-libXinerama-1.1.5-dev/lib/pkgconfig
      - /nix/store/lrq6kg1h76pzxhwb7b9zqjj0mbkwjhb2-cups-2.4.8-dev/lib/pkgconfig
      - /nix/store/hsx0g1wnb7gckvvg51j056n84gyhgghw-gmp-with-cxx-6.3.0-dev/lib/pkgconfig
      - /nix/store/ga5aqq7852lwk9df3fkms7rk3zm6nsgi-webkitgtk-2.44.2+abi=4.0-dev/lib/pkgconfig
      - /nix/store/9xlfkwlg6qas2rkg8qgl6f9ja2qdzgih-sqlite-3.45.3-dev/lib/pkgconfig
      - /nix/store/dkps96575fb7aw60vgjcvk5s1fv73axa-libudev-zero-1.0.3/lib/pkgconfig

  HINT: you may need to install a package such as libsoup-3.0, libsoup-3.0-dev or libsoup-3.0-devel.
```
It seems a package is missing ?

**Comment by mwaurawakati** [comment]
Install the package

**Comment by AkechiShiro** [comment]
@mwaurawakati you should update the flake, instead of editing the cargo.toml file.

For packages, those should be declared in the flake too.

**Comment by AkechiShiro** [comment]
I moved on ArchLinux for easier pkgs install, but the compilation still fails : 
```rust
error[E0432]: unresolved import `tauri::tray::ClickType`
  --> src/lib.rs:10:12
   |
10 |     tray::{ClickType, TrayIconBuilder},
   |            ^^^^^^^^^ no `ClickType` in `tray`

error[E0599]: no method named `emit` found for reference `&AppHandle` in the current scope
   --> src/app/global_app.rs:24:36
    |
24  |                 let _ = app_handle.emit(event, payload);
    |                                    ^^^^
    |
    = help: items from traits can only be used if the trait is in scope
help: there is a method `exit` with a similar name, but with different arguments
   --> /home/garudadev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-2.0.0-beta.24/src/app.rs:412:3
    |
412 |   pub fn exit(&self, exit_code: i32) {
    |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
help: trait `Emitter` which provides `emit` is implemented but not in scope; perhaps you want to import it
    |
2   + use tauri::Emitter;
    |

error[E0609]: no field `click_type` on type `tauri::tray::TrayIconEvent`
  --> src/lib.rs:36:30
   |
36 |                     if event.click_type == ClickType::Left {
   |                              ^^^^^^^^^^ unknown field

warning: unused import: `Manager`
 --> src/app/global_app.rs:5:24
  |
5 | use tauri::{AppHandle, Manager};
  |                        ^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

Some errors have detailed explanations: E0432, E0599, E0609.
For more information about an error, try `rustc --explain E0432`.
warning: `aegis-gui-tauri` (lib) generated 1 warning
error: could not compile `aegis-gui-tauri` (lib) due to 3 previous errors; 1 warning emitted
```

**Comment by mwaurawakati** [comment]
You are using tauri 1.0. This pull request was for tauri v2.0. I will close it

**Comment by AkechiShiro** [comment]
I'm using tauri v2, the compilation bugs are because of breaking changes in tauri v2 that haven't been fixed in the code.

**Comment by AkechiShiro** [comment]
I fixed everything and it is still failing to start at the moment : 
image

@mwaurawakati  not sure why you are closing the PR, I think it's better than nothing to convert the app to use tauri v2.

**Comment by mwaurawakati** [comment]
Before opening the pull request, I made sure it was working. I am no longer working on this project actively. If the pull request is not working, it's more logical to close it.

**Comment by AkechiShiro** [comment]
I'll try to fix it, it is a lot of changes, if you have any advice on investigating the null ptr dereference, feel free to let me know. Thanks for your work on this project.

**Comment by mwaurawakati** [comment]
I have no advice to give.

**Pull request closed without merging**
